replicaCount: 2

image:
  repository: ghcr.io/your-org/ml-pipeline-prep   # <-- set to your registry
  tag: dev                                        # <-- set to your git SHA in dev
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources:
  requests: { cpu: "500m", memory: "512Mi" }
  limits:   { cpu: "1",    memory: "1Gi" }

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 65

podAnnotations: {}
podLabels: {}
imagePullSecrets: []   # e.g., [{ name: regcred }]

# Map of env vars consumed by src/common/config.py, src/prep_api/app.py
env:
  SERVICE_NAME: "prep"
  NAMESPACE: "dev"
  QUEUE_BACKEND: "kafka"
  KAFKA_BOOTSTRAP: "redpanda:9092"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  TOPIC_PRE: "preprocessed-data"
  TOPIC_PREFIX: ""
  BUCKET_PREFIX: ""
  S3_ENDPOINT: "http://minio:9000"
  S3_ENDPOINT_PUBLIC: "http://localhost:9000"
  S3_ACCESS_KEY: "minioadmin"
  S3_SECRET_KEY: "minioadmin"
  BUCKET_RAW: "raw"
  BUCKET_PRE: "pre"
  BUCKET_MODELS: "models"
  ALLOW_ORIGINS: "*"
  BUILD_SHA: "dev"

extraEnv: []   # list of {name,value} for quick additions

nodeSelector: {}
affinity: {}
tolerations: []
