name: ml-pipeline-v2

services:
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
    command: ["redis-server","--save","","--appendonly","no"]

  minio:
    image: minio/minio:RELEASE.2024-08-17T01-24-54Z
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports: ["9000:9000","9001:9001"]
    volumes:
      - minio-data:/data

  redpanda:
    image: redpandadata/redpanda:v24.1.10
    command:
      - redpanda start
      - --overprovisioned
      - --smp=1
      - --memory=1G
      - --reserve-memory=0M
      - --node-id=0
      - --check=false
      - --kafka-addr=PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr=PLAINTEXT://redpanda:9092
    ports: ["9092:9092"]

  prep:
    build:
      context: .
      dockerfile: docker/Dockerfile.prep
    environment:
      SERVICE_NAME: "prep"
      NAMESPACE: "dev"
      # Transport: Kafka; Status: Redis
      QUEUE_BACKEND: "kafka"
      KAFKA_BOOTSTRAP: "redpanda:9092"
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
      # Topics (shared with train)
      TOPIC_PRE: "preprocessed-data"
      # Replication prefixes (optional; leave blank to disable)
      TOPIC_PREFIX: ""
      BUCKET_PREFIX: ""
      # MinIO (S3)
      S3_ENDPOINT: "http://minio:9000"
      S3_ACCESS_KEY: "minioadmin"
      S3_SECRET_KEY: "minioadmin"
      BUCKET_RAW: "raw"
      BUCKET_PRE: "pre"
      BUCKET_MODELS: "models"
      # For presigned URLs usable from host (optional, recommended)
      S3_ENDPOINT_PUBLIC: "http://localhost:9000"
    ports: ["8000:8080"]
    depends_on: [redis, minio, redpanda]

  train:
    build:
      context: .
      dockerfile: docker/Dockerfile.train
    environment:
      SERVICE_NAME: "train"
      NAMESPACE: "dev"
      # Transport: Kafka; Status: Redis
      QUEUE_BACKEND: "kafka"
      KAFKA_BOOTSTRAP: "redpanda:9092"
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
      # Topics (shared with prep)
      TOPIC_PRE: "preprocessed-data"
      TOPIC_PREFIX: ""
      # MinIO (S3)
      S3_ENDPOINT: "http://minio:9000"
      S3_ACCESS_KEY: "minioadmin"
      S3_SECRET_KEY: "minioadmin"
      BUCKET_RAW: "raw"
      BUCKET_PRE: "pre"
      BUCKET_MODELS: "models"
      TRAIN_MAX_RUNTIME_S: "600"
    ports: ["8001:8080"]
    depends_on: [redis, minio, redpanda]

volumes:
  minio-data: {}
