replicaCount: 2

image:
  repository: ghcr.io/your-org/ml-pipeline-train
  tag: dev
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources:
  requests: { cpu: "1", memory: "1Gi" }
  limits:   { cpu: "2", memory: "2Gi" }

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

podAnnotations: {}
podLabels: {}
imagePullSecrets: []

env:
  SERVICE_NAME: "train"
  NAMESPACE: "dev"
  QUEUE_BACKEND: "kafka"
  KAFKA_BOOTSTRAP: "redpanda:9092"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  TOPIC_PRE: "preprocessed-data"
  TOPIC_PREFIX: ""
  BUCKET_PREFIX: ""
  S3_ENDPOINT: "http://minio:9000"
  S3_ACCESS_KEY: "minioadmin"
  S3_SECRET_KEY: "minioadmin"
  BUCKET_RAW: "raw"
  BUCKET_PRE: "pre"
  BUCKET_MODELS: "models"
  TRAIN_MAX_RUNTIME_S: "600"
  BUILD_SHA: "dev"

extraEnv: []

nodeSelector: {}
affinity: {}
tolerations: []
