apiVersion: apps/v1
kind: Deployment
metadata:
  name: prep-prep
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prep
  template:
    metadata:
      labels:
        app: prep
    spec:
      containers:
      - name: prep
        image: ml-pipeline/prep:dev  
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080   
        env:
        - name: S3_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: ml-app-secrets
              key: S3_ENDPOINT
        - name: S3_BUCKET
          valueFrom:
            secretKeyRef:
              name: ml-app-secrets
              key: S3_BUCKET
        - name: S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: ml-app-secrets
              key: S3_ACCESS_KEY
        - name: S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: ml-app-secrets
              key: S3_SECRET_KEY
        - name: ENV
          valueFrom:
            secretKeyRef:
              name: ml-app-secrets
              key: ENV
