apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-train
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: train
  template:
    metadata:
      labels:
        app: train
    spec:
      containers:
        - name: train
          image: ml-pipeline/train:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: ml-app-secrets
      restartPolicy: Always
